### PR TITLE
MINOR: Execute script py python3 by default

### PR DESCRIPTION
**Pull request by LLluma**

### CODE REVIEW

**Comment by mattjegan** [comment]
@LLluma I don't think this change is needed. It may actually be a breaking change for some users that may not have python 3 installed.

**Comment by LLluma** [comment]
But in code is using "print()" function from python3. In python2 is using "print" statement.
So, to run this code needs python3 anyway.
Or instead of "print" function can be used sys.stderr.write function. It this case code will be backward compatible with python2.

**Comment by mattjegan** [comment]
Ok, so Python 2 can actually support `print("content")` but Python 3 cannot support `print "content"` so we take the safe road by just using `print("content")` everywhere that way Python 2 and 3 are supported.

**Comment by LLluma** [comment]
Hm... I'm surprised =). I thought for using print function in python2 needs to import if from future.
`from __future__ import print_function`.
But it works somehow without that.

**Pull request closed without merging**
