### PR TITLE
fixes #17, adds integration for command = pid 

### LINKED ISSUE #17: Feature Proposal: Attach HowLong to a running process
Can we have a feature to attach to an already running process and give timing stats about that? 

I regularly come across this scenario when I am running heavy resource intensive processes [say Linux kernel compilation or Android AOSP builds or downloading system updates]. It is fairly easy to forget running the command under `howlong` or *nix's `time` while launching the process. It would be great to keep track of how long something has been running even after it has been started. 

I have a fairly solid knowledge of achieving that in Linux systems with `proc` support. Not sure about other operating systems, though. 

Would love to hear your thoughts about this.

### PR DESCRIPTION
**Pull request by kennethgoodman**
with the arguments being the pid

### CODE REVIEW

**Comment by mattjegan** [comment]
Hey @kennethgoodman , thanks for PR! Looks pretty good to me, would you be able to change some things before I merge it in thanks? 

- could you please add `psutil` to the `requirements.txt` file?
- I think it would be best to have the `pid` command as a flag, something like `--pid` or `-p` followed by the process id.

If you've got any questions feel free to ask, much appreciated.

**Comment by kennethgoodman** [comment]
> could you please add psutil to the requirements.txt file?

yes

> I think it would be best to have the pid command as a flag, something like --pid or -p followed by the process id.

I did this originally, but realized the command argument would need to be optional, and a flag would have to be passed, this is why I choose this option. What are your thoughts?

Also, I think I'll also move the Process class into its own file, this may get bigger as we add CPU stats and what not.

**Comment by mattjegan** [comment]
@kennethgoodman I think I still prefer the flag, I'm fine with switching the command to be optional, perhaps a `-c` or `--cmd`. As the project is quite small I think this is fine to break.

**Comment by mattjegan** [comment]
All good and merged in, thanks for the PR 👍

**Pull request merged**
