### PR TITLE
Colored text functionality

### PR DESCRIPTION
**Pull request by aniketrege**
Added colored text option to log messages using termcolor package. Specified this package in install_requires in setup file.

### CODE REVIEW

**Comment by mattjegan** [comment]
Thanks for the enthusiasm with these PRs, however with the coloring we are hoping to use `colorama` as discussed in #20

**Review by mattjegan — APPROVED** [review]
Looks good to me

**Comment by mattjegan** [comment]
@aniketrege you'll need to add `termcolor` and `colorama` both to the `install_requires` and `requirements.txt` before I merge so that TravisCI can pass 😄

**Comment by aniketrege** [comment]
Hi Matt, I'll add those too

**Comment by mattjegan** [comment]
I'm going to merge this anyway but next time can you please put the requirement changes in the PR that makes the initial changes (https://github.com/mattjegan/HowLong/pull/26)

**Pull request merged**
